from fastapi import FastAPI, APIRouter
import json

router = APIRouter()

customers = '''[
{
    "params": {
        "limit": 50,
        "page": 1,
        "store_id": 1374789,
        "customer_id_or_code": "29557436"
    },
    "data": {
        "customer": {
            "store_id": 1374789,
            "total_order": 0,
            "total_spent": "0.0",
            "birthdate": "1995-02-08",
            "id": 29557436,
            "user_id": null,
            "pricelist_id": null,
            "email": "tester@gmail.com",
            "first_name": "Tester",
            "last_name": null,
            "phone": "+6578978991",
            "gender": "male",
            "country_code": "SG",
            "accepts_marketing": true,
            "avatar_url": "https://assets.imgix.net/~text?bg=6F0062\u0026txtclr=ffffff\u0026w=200\u0026h=200\u0026txtsize=90\u0026txt=TE\u0026txtfont=Helvetica\u0026txtalign=middle,center",
            "origin_avatar_url": null,
            "locale": "en_US",
            "total_credit": "0.0",
            "first_paid_order_id": null,
            "last_order_id": null,
            "last_order": null,
            "last_order_at": null,
            "wholesale_enabled": false,
            "source": "admin",
            "app_id": null,
            "lead_source": "admin_panel",
            "creation_source": null,
            "code": "A0029557436D",
            "note": "",
            "customer_code": null,
            "registration_location_id": null,
            "attribution_location_id": null,
            "attribution_user_id": null,
            "is_verified": false,
            "is_blacklisted": false,
            "is_lead": false,
            "is_deleted": false,
            "deleted_at": null,
            "birthday_last_updated_at": null,
            "updated_at": "2025-02-26T13:56:48.000+08:00",
            "created_at": "2025-02-26T13:56:48.000+08:00",
            "deletion_job_id": null,
            "name": "Tester ",
            "display_name": "Tester",
            "birthday": "2026-02-08",
            "zodiac": "aquarius",
            "credentials": {
                "email": "tester@gmail.com",
                "phone": "+6578978991"
            },
            "barcode_url": "https://easy.co/c/29557436/barcode.svg?hmac=78b897f02b386519280d9a9755474e36dad04a2c13d910a3ec0335620fb533c5",
            "qrcode_url": "https://easy.co/c/29557436/qrcode.svg?hmac=78b897f02b386519280d9a9755474e36dad04a2c13d910a3ec0335620fb533c5",
            "birthdate_editable": false,
            "country": "Singapore",
            "authentications": {
                "email": {
                    "account": "tester@gmail.com",
                    "is_connected": true,
                    "is_verified": false,
                    "verifiable": true
                },
                "line": {
                    "account": null,
                    "is_connected": false,
                    "is_verified": false
                },
                "facebook": {
                    "account": null,
                    "is_connected": false,
                    "is_verified": false
                }
            },
            "has_password": false,
            "purchased_channels": [],
            "attributes": [],
            "company": "EasyStore",
            "address1": "435 ORCHARD ROAD 19-03 WISMA ATRIA",
            "address2": "",
            "city": "Singapore",
            "zip": "238877",
            "sub_district": null,
            "sub_district_code": null,
            "district": null,
            "district_code": null,
            "province": "Central Singapore",
            "province_code": "SG-01",
            "groups": []
        },
        "membership_tiers": [],
        "summary": {
            "total_purchases": 0,
            "total_spent": 0.0,
            "average_spent": 0.0
        },
        "orders": [],
        "bought_items": [],
        "addresses": [
            {
                "id": 24324616,
                "customer_id": 29557436,
                "name": "Tester EasyStore",
                "first_name": "Tester",
                "last_name": "EasyStore",
                "company": "EasyStore",
                "address1": "435 ORCHARD ROAD 19-03 WISMA ATRIA",
                "address2": "",
                "city": "Singapore",
                "zip": "238877",
                "village": null,
                "sub_district": null,
                "sub_district_code": null,
                "district": null,
                "district_code": null,
                "province": "Central Singapore",
                "province_code": "SG-01",
                "country": "Singapore",
                "country_code": "SG",
                "phone": "+6578978991",
                "is_primary": true,
                "updated_at": "2025-02-26T13:58:16.000+08:00",
                "created_at": "2025-02-26T13:58:05.000+08:00",
                "email": "tester@gmail.com"
            }
        ],
        "prev_next": {
            "prev_id": null,
            "next_id": 29274634,
            "params": {
                "limit": 50,
                "page": 1,
                "store_id": 1374789,
                "customer_id_or_code": "29557436"
            }
        },
        "admin_links": null
    }
},
{
    "params": {
        "limit": 50,
        "page": 1,
        "store_id": 1374789,
        "customer_id_or_code": "29274634"
    },
    "data": {
        "customer": {
            "store_id": 1374789,
            "total_order": 0,
            "total_spent": "0.0",
            "birthdate": null,
            "id": 29274634,
            "user_id": null,
            "pricelist_id": null,
            "email": "kah.yan@kingstech.com.sg",
            "first_name": "Kah Yan Kingstech",
            "last_name": null,
            "phone": "60169316170",
            "gender": null,
            "country_code": "SG",
            "accepts_marketing": false,
            "avatar_url": "https://assets.imgix.net/~text?bg=001E09\u0026txtclr=ffffff\u0026w=200\u0026h=200\u0026txtsize=90\u0026txt=KA\u0026txtfont=Helvetica\u0026txtalign=middle,center",
            "origin_avatar_url": null,
            "locale": "en_US",
            "total_credit": "0.0",
            "first_paid_order_id": null,
            "last_order_id": null,
            "last_order": null,
            "last_order_at": null,
            "wholesale_enabled": false,
            "source": "shopping_app",
            "app_id": null,
            "lead_source": "shopping_app",
            "creation_source": "online_store",
            "code": "O0029274634S",
            "note": null,
            "customer_code": null,
            "registration_location_id": null,
            "attribution_location_id": null,
            "attribution_user_id": null,
            "is_verified": false,
            "is_blacklisted": false,
            "is_lead": false,
            "is_deleted": false,
            "deleted_at": null,
            "birthday_last_updated_at": null,
            "updated_at": "2025-02-24T09:23:58.000+08:00",
            "created_at": "2025-02-10T15:59:23.000+08:00",
            "deletion_job_id": null,
            "name": "Kah Yan Kingstech ",
            "display_name": "Kah Yan Kingstech",
            "birthday": null,
            "zodiac": null,
            "credentials": {
                "email": "kah.yan@kingstech.com.sg",
                "phone": "+60169316170"
            },
            "barcode_url": "https://easy.co/c/29274634/barcode.svg?hmac=a4071e92d50062b0057bee3883bf133cd32364781da02ec995acf4592a57c8c3",
            "qrcode_url": "https://easy.co/c/29274634/qrcode.svg?hmac=a4071e92d50062b0057bee3883bf133cd32364781da02ec995acf4592a57c8c3",
            "birthdate_editable": true,
            "country": "Singapore",
            "authentications": {
                "email": {
                    "account": "kah.yan@kingstech.com.sg",
                    "is_connected": true,
                    "is_verified": false,
                    "verifiable": true
                },
                "line": {
                    "account": null,
                    "is_connected": false,
                    "is_verified": false
                },
                "facebook": {
                    "account": null,
                    "is_connected": false,
                    "is_verified": false
                }
            },
            "has_password": true,
            "purchased_channels": [
                "sf"
            ],
            "attributes": [],
            "company": "",
            "address1": "No.5 Jurong East St 32 #13-04",
            "address2": "",
            "city": "Singapore",
            "zip": "609479",
            "sub_district": null,
            "sub_district_code": null,
            "district": null,
            "district_code": null,
            "province": "Central Singapore",
            "province_code": "SG-01",
            "groups": []
        },
        "membership_tiers": [],
        "summary": {
            "total_purchases": 0,
            "total_spent": 0.0,
            "average_spent": 0.0
        },
        "orders": [
            {
                "id": 80719466,
                "store_id": 1374789,
                "customer_id": 29274634,
                "location_id": null,
                "user_id": null,
                "user_type": null,
                "app_id": null,
                "product_catalog_id": null,
                "name": "#1001",
                "number": 1001,
                "order_number": "#1001",
                "base_currency": null,
                "currency": "SGD",
                "currency_rate": "1.0",
                "currency_decimals": 2,
                "total_line_items_price": "54.8",
                "total_discount": "5.0",
                "custom_discount": "0.0",
                "shipping_discount": "3.75",
                "subtotal_price": "54.8",
                "taxes_included": false,
                "credit_used": "0.00",
                "credit_earn": "0.00",
                "total_shipping": "3.75",
                "total_tax": "0.0",
                "total_rounding": "0.0",
                "total_price": "49.8",
                "total_amount_include_transaction": "49.8",
                "transaction_charge_fee": "0.0",
                "transaction_charge_rate_fee": "0.0",
                "refund_amount": "0.0",
                "transaction_charge_rate": 0.0,
                "discount_id": null,
                "discount_code": null,
                "note": "seller note, send out by 28/02/2025",
                "note_attributes": [],
                "remark": "Test",
                "token": "257a9827-70ee-4787-8f72-4e1bc8af7a9f",
                "cart_token": "14ae6a36-0b9a-4c84-8176-0d54cbc87665",
                "source_name": "sf",
                "source_type": "online_store",
                "browser_ip": "2402:b400:4640:598e:f8ae:e625:2121:9d92",
                "landing_site": null,
                "referring_site": "https://kingstech.easy.co/",
                "fulfillment_status": "unfulfilled",
                "display_fulfillment_status": "unfulfilled",
                "financial_status": "unpaid",
                "payment_status": true,
                "cod_type": false,
                "os_info": "windows",
                "device_type": "desktop",
                "client_info": "chrome",
                "user_agent": {
                    "brand": "",
                    "model": "",
                    "device": "desktop",
                    "osInfo": {
                        "name": "Windows",
                        "version": "10",
                        "platform": "x64",
                        "short_name": "WIN"
                    },
                    "clientInfo": {
                        "name": "Chrome",
                        "type": "browser",
                        "engine": "Blink",
                        "version": "132.0.0.0",
                        "short_name": "CH",
                        "engine_version": ""
                    },
                    "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/132.0.0.0 Safari/537.36"
                },
                "is_processed": true,
                "is_archived": false,
                "is_cancelled": false,
                "is_deleted": false,
                "is_completed": true,
                "is_recovered": false,
                "is_restocked": false,
                "deleted_at": null,
                "cancelled_at": null,
                "archived_at": null,
                "processed_at": "2025-02-12T13:44:57.000+08:00",
                "closed_at": null,
                "pending_at": null,
                "paid_at": null,
                "updated_at": "2025-02-26T15:11:40.000+08:00",
                "created_at": "2025-02-10T15:14:11.000+08:00",
                "first_name": "Kah Yan Kingstech",
                "last_name": null,
                "email": "kah.yan@kingstech.com.sg",
                "phone": "60169316170",
                "company": "",
                "address1": "No.5 Jurong East St 32 #13-04",
                "address2": "",
                "zip": "609479",
                "city": "Singapore",
                "sub_district": null,
                "district": null,
                "province": "Central Singapore",
                "country": "Singapore",
                "village": null,
                "has_attachment": true,
                "channel": "storefront",
                "is_refunded": false,
                "is_backordered": false,
                "payment_url": "https://kingstech.easy.co/orders/14ae6a36-0b9a-4c84-8176-0d54cbc87665",
                "currency_prefix": "S$",
                "currency_suffix": null,
                "thousand_separator": ",",
                "barcode": "ES80719466OR",
                "barcode_image_url": "https://barcodeapi.org/api/128/ES80719466OR?text=none",
                "is_pickup_from_store_location": false,
                "display_name": "Kah Yan Kingstech",
                "device_client": {
                    "brand": "",
                    "model": "",
                    "device": "desktop",
                    "osInfo": {
                        "name": "Windows",
                        "version": "10",
                        "platform": "x64",
                        "short_name": "WIN"
                    },
                    "clientInfo": {
                        "name": "chrome",
                        "type": "browser",
                        "engine": "Blink",
                        "version": "132.0.0.0",
                        "short_name": "CH",
                        "engine_version": ""
                    },
                    "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/132.0.0.0 Safari/537.36"
                },
                "original_fulfillment_status": "unfulfilled",
                "fulfilled_item_quantity": 0,
                "items": [
                    {
                        "id": 180936686,
                        "order_id": 80719466,
                        "product_id": 13322534,
                        "variant_id": 61761716,
                        "discount_id": null,
                        "product_name": "WEKOME WP-19 Fast Charging Mini 3-in-1 5000mAh Power Bank",
                        "variant_name": "Beige",
                        "sku": "6941027649435",
                        "barcode": null,
                        "price": "29.0",
                        "cost_price": "0.0",
                        "total_discount": "0.0",
                        "discount_applies_once": null,
                        "grams": "500.0",
                        "width": "7.0",
                        "height": "3.0",
                        "length": "2.0",
                        "quantity": 1,
                        "backorder_quantity": 0,
                        "taxable": false,
                        "shipping_required": true,
                        "components_required": false,
                        "total_tax": "0.0",
                        "is_custom_price": false,
                        "is_deleted": false,
                        "deleted_at": null,
                        "delete_from": null,
                        "created_from": "cp",
                        "updated_at": "2025-02-26T15:10:24.000+08:00",
                        "created_at": "2025-02-26T15:10:24.000+08:00",
                        "inventory_management": "easystore",
                        "total_amount": "29.0",
                        "subtotal": "29.0",
                        "barcode_image": "",
                        "variant_count": 3,
                        "restocked_quantity": 0,
                        "restockable_quantity": 1,
                        "fulfilled_quantity": 0,
                        "fulfillable_quantity": 1,
                        "fulfillment_service": [],
                        "returns": null,
                        "returned_quantity": 0,
                        "returnable_quantity": 0,
                        "exchanged_quantity": 0,
                        "properties": [],
                        "vendors": [],
                        "original_line_price": "29.0",
                        "final_line_price": "29.0",
                        "quantity_before_edit": 1,
                        "image_url": "https://cdn.store-assets.com/s/1374789/i/83082035.jpg",
                        "shipping_condition": "general",
                        "shipping_profile": {
                            "id": 534725,
                            "name": "Default Profile",
                            "condition": "general"
                        },
                        "line_item_group": {}
                    },
                    {
                        "id": 180936721,
                        "order_id": 80719466,
                        "product_id": 13322526,
                        "variant_id": 61761598,
                        "discount_id": null,
                        "product_name": "Wekome WDC-47 Magnetic Data Cable 65W 1M(PD 35W)",
                        "variant_name": null,
                        "sku": "6941027650202",
                        "barcode": null,
                        "price": "12.9",
                        "cost_price": "0.0",
                        "total_discount": "0.0",
                        "discount_applies_once": null,
                        "grams": "300.0",
                        "width": "7.0",
                        "height": "3.0",
                        "length": "2.0",
                        "quantity": 2,
                        "backorder_quantity": 0,
                        "taxable": false,
                        "shipping_required": true,
                        "components_required": false,
                        "total_tax": "0.0",
                        "is_custom_price": false,
                        "is_deleted": false,
                        "deleted_at": null,
                        "delete_from": null,
                        "created_from": "cp",
                        "updated_at": "2025-02-26T15:10:55.000+08:00",
                        "created_at": "2025-02-26T15:10:49.000+08:00",
                        "inventory_management": "easystore",
                        "total_amount": "25.8",
                        "subtotal": "25.8",
                        "barcode_image": "",
                        "variant_count": 1,
                        "restocked_quantity": 0,
                        "restockable_quantity": 2,
                        "fulfilled_quantity": 0,
                        "fulfillable_quantity": 2,
                        "fulfillment_service": [],
                        "returns": null,
                        "returned_quantity": 0,
                        "returnable_quantity": 0,
                        "exchanged_quantity": 0,
                        "properties": [],
                        "vendors": [],
                        "original_line_price": "25.8",
                        "final_line_price": "25.8",
                        "quantity_before_edit": 2,
                        "image_url": "https://cdn.store-assets.com/s/1374789/i/83081961.jpg",
                        "shipping_condition": "general",
                        "shipping_profile": {
                            "id": 534725,
                            "name": "Default Profile",
                            "condition": "general"
                        },
                        "line_item_group": {}
                    }
                ],
                "total_item_quantity": 3,
                "total_discount_amount": "5.0",
                "sales_channel_metafield": null,
                "referral": null,
                "last_transaction_method": "bank-transfer",
                "amount": "49.8"
            }
        ],
        "bought_items": [],
        "addresses": [
            {
                "id": 24083172,
                "customer_id": 29274634,
                "name": "Kah Yan Looi",
                "first_name": "Kah Yan",
                "last_name": "Looi",
                "company": "",
                "address1": "No.5 Jurong East St 32 #13-04",
                "address2": "",
                "city": "Singapore",
                "zip": "609479",
                "village": null,
                "sub_district": null,
                "sub_district_code": null,
                "district": null,
                "district_code": null,
                "province": "Central Singapore",
                "province_code": "SG-01",
                "country": "Singapore",
                "country_code": "SG",
                "phone": "+60169316170",
                "is_primary": true,
                "updated_at": "2025-02-12T13:44:57.000+08:00",
                "created_at": "2025-02-12T13:44:57.000+08:00",
                "email": "kah.yan@kingstech.com.sg"
            }
        ],
        "prev_next": {
            "prev_id": 29557436,
            "next_id": null,
            "params": {
                "limit": 50,
                "page": 1,
                "store_id": 1374789,
                "customer_id_or_code": "29274634"
            }
        },
        "admin_links": null
    }
}
]'''

customers = json.loads(customers)

@router.get("/api/customers")
async def get_collections():
    return customers