from fastapi import FastAPI, APIRouter
import json

router = APIRouter()

inventories = '''[

{
    "docs": [
        {
            "name": "MAT-STE-2025-00026",
            "owner": "kah.yan@kingstech.com.sg",
            "creation": "2025-03-06 14:30:34.458278",
            "modified": "2025-03-06 14:30:38.160405",
            "modified_by": "kah.yan@kingstech.com.sg",
            "docstatus": 1,
            "idx": 0,
            "naming_series": "MAT-STE-.YYYY.-",
            "stock_entry_type": "Material Receipt",
            "purpose": "Material Receipt",
            "add_to_transit": 0,
            "company": "SWIFTLY STORE PTE LTD",
            "posting_date": "2025-03-06",
            "posting_time": "14:30:38.252797",
            "set_posting_time": 0,
            "inspection_required": 0,
            "apply_putaway_rule": 0,
            "from_bom": 0,
            "use_multi_level_bom": 1,
            "fg_completed_qty": 0.0,
            "process_loss_percentage": 0.0,
            "process_loss_qty": 0.0,
            "total_outgoing_value": 0.0,
            "total_incoming_value": 8500.0,
            "value_difference": 8500.0,
            "total_additional_costs": 0.0,
            "letter_head": "SALES INVOICE",
            "is_opening": "No",
            "per_transferred": 0.0,
            "total_amount": 8500.0,
            "is_return": 0,
            "doctype": "Stock Entry",
            "additional_costs": [],
            "items": [
                {
                    "name": "p2j9e281pa",
                    "owner": "kah.yan@kingstech.com.sg",
                    "creation": "2025-03-06 14:30:34.458278",
                    "modified": "2025-03-06 14:30:38.160405",
                    "modified_by": "kah.yan@kingstech.com.sg",
                    "docstatus": 1,
                    "idx": 1,
                    "has_item_scanned": 0,
                    "t_warehouse": "EasyStore - SSPL",
                    "item_code": "61761695",
                    "item_name": "WEKOME WP-45 Magnetic Wireless Power Bank 10000mAh Fast Charge 15W",
                    "is_finished_item": 0,
                    "is_scrap_item": 0,
                    "description": "TheWEKOME WP-45 Magnetic Wireless Power Bankis a sleek and versatile charging solution, designed to meet the demands of modern, on-the-go lifestyles. With a powerful10000mAh capacity, it offers ample energy to keep your devices powered throughout the",
                    "item_group": "10000mAh",
                    "image": "https://cdn.store-assets.com/s/1374789/i/83082021.jpg",
                    "qty": 100.0,
                    "transfer_qty": 100.0,
                    "retain_sample": 0,
                    "uom": "Unit",
                    "stock_uom": "Unit",
                    "conversion_factor": 1.0,
                    "sample_quantity": 0,
                    "basic_rate": 20.0,
                    "additional_cost": 0.0,
                    "valuation_rate": 20.0,
                    "allow_zero_valuation_rate": 0,
                    "set_basic_rate_manually": 0,
                    "basic_amount": 2000.0,
                    "amount": 2000.0,
                    "expense_account": "6-S00007 - Stock adjustment - SSPL",
                    "cost_center": "Main - SSPL",
                    "actual_qty": 0.0,
                    "transferred_qty": 0.0,
                    "allow_alternative_item": 0,
                    "parent": "MAT-STE-2025-00026",
                    "parentfield": "items",
                    "parenttype": "Stock Entry",
                    "doctype": "Stock Entry Detail"
                },
                {
                    "name": "p2j921m44b",
                    "owner": "kah.yan@kingstech.com.sg",
                    "creation": "2025-03-06 14:30:34.458278",
                    "modified": "2025-03-06 14:30:38.160405",
                    "modified_by": "kah.yan@kingstech.com.sg",
                    "docstatus": 1,
                    "idx": 2,
                    "has_item_scanned": 0,
                    "t_warehouse": "EasyStore - SSPL",
                    "item_code": "61761721",
                    "item_name": "WEKOME WP-19 Fast Charging Mini 3-in-1 5000mAh Power Bank - GRE",
                    "is_finished_item": 0,
                    "is_scrap_item": 0,
                    "description": "WEKOME WP-19 Fast Charging Mini 3-in-1 5000mAh Power Bank - GRE",
                    "item_group": "5000mAh",
                    "image": "https://cdn.store-assets.com/s/1374789/i/83082037.jpg",
                    "qty": 100.0,
                    "transfer_qty": 100.0,
                    "retain_sample": 0,
                    "uom": "Unit",
                    "stock_uom": "Unit",
                    "conversion_factor": 1.0,
                    "sample_quantity": 0,
                    "basic_rate": 20.0,
                    "additional_cost": 0.0,
                    "valuation_rate": 20.0,
                    "allow_zero_valuation_rate": 0,
                    "set_basic_rate_manually": 0,
                    "basic_amount": 2000.0,
                    "amount": 2000.0,
                    "expense_account": "6-S00007 - Stock adjustment - SSPL",
                    "cost_center": "Main - SSPL",
                    "actual_qty": 0.0,
                    "transferred_qty": 0.0,
                    "allow_alternative_item": 0,
                    "parent": "MAT-STE-2025-00026",
                    "parentfield": "items",
                    "parenttype": "Stock Entry",
                    "doctype": "Stock Entry Detail"
                },
                {
                    "name": "p2j9om41ej",
                    "owner": "kah.yan@kingstech.com.sg",
                    "creation": "2025-03-06 14:30:34.458278",
                    "modified": "2025-03-06 14:30:38.160405",
                    "modified_by": "kah.yan@kingstech.com.sg",
                    "docstatus": 1,
                    "idx": 3,
                    "has_item_scanned": 0,
                    "t_warehouse": "EasyStore - SSPL",
                    "item_code": "61761716",
                    "item_name": "WEKOME WP-19 Fast Charging Mini 3-in-1 5000mAh Power Bank - BEI",
                    "is_finished_item": 0,
                    "is_scrap_item": 0,
                    "description": "WEKOME WP-19 Fast Charging Mini 3-in-1 5000mAh Power Bank - BEI",
                    "item_group": "5000mAh",
                    "image": "https://cdn.store-assets.com/s/1374789/i/83082035.jpg",
                    "qty": 100.0,
                    "transfer_qty": 100.0,
                    "retain_sample": 0,
                    "uom": "Unit",
                    "stock_uom": "Unit",
                    "conversion_factor": 1.0,
                    "sample_quantity": 0,
                    "basic_rate": 20.0,
                    "additional_cost": 0.0,
                    "valuation_rate": 20.0,
                    "allow_zero_valuation_rate": 0,
                    "set_basic_rate_manually": 0,
                    "basic_amount": 2000.0,
                    "amount": 2000.0,
                    "expense_account": "6-S00007 - Stock adjustment - SSPL",
                    "cost_center": "Main - SSPL",
                    "actual_qty": 0.0,
                    "transferred_qty": 0.0,
                    "allow_alternative_item": 0,
                    "parent": "MAT-STE-2025-00026",
                    "parentfield": "items",
                    "parenttype": "Stock Entry",
                    "doctype": "Stock Entry Detail"
                },
                {
                    "name": "p2j9qsnf3m",
                    "owner": "kah.yan@kingstech.com.sg",
                    "creation": "2025-03-06 14:30:34.458278",
                    "modified": "2025-03-06 14:30:38.160405",
                    "modified_by": "kah.yan@kingstech.com.sg",
                    "docstatus": 1,
                    "idx": 4,
                    "has_item_scanned": 0,
                    "t_warehouse": "EasyStore - SSPL",
                    "item_code": "61761719",
                    "item_name": "WEKOME WP-19 Fast Charging Mini 3-in-1 5000mAh Power Bank - BLA",
                    "is_finished_item": 0,
                    "is_scrap_item": 0,
                    "description": "WEKOME WP-19 Fast Charging Mini 3-in-1 5000mAh Power Bank - BLA",
                    "item_group": "5000mAh",
                    "image": "https://cdn.store-assets.com/s/1374789/i/83082040.jpg",
                    "qty": 100.0,
                    "transfer_qty": 100.0,
                    "retain_sample": 0,
                    "uom": "Unit",
                    "stock_uom": "Unit",
                    "conversion_factor": 1.0,
                    "sample_quantity": 0,
                    "basic_rate": 20.0,
                    "additional_cost": 0.0,
                    "valuation_rate": 20.0,
                    "allow_zero_valuation_rate": 0,
                    "set_basic_rate_manually": 0,
                    "basic_amount": 2000.0,
                    "amount": 2000.0,
                    "expense_account": "6-S00007 - Stock adjustment - SSPL",
                    "cost_center": "Main - SSPL",
                    "actual_qty": 0.0,
                    "transferred_qty": 0.0,
                    "allow_alternative_item": 0,
                    "parent": "MAT-STE-2025-00026",
                    "parentfield": "items",
                    "parenttype": "Stock Entry",
                    "doctype": "Stock Entry Detail"
                },
                {
                    "name": "p2j9fa5sr4",
                    "owner": "kah.yan@kingstech.com.sg",
                    "creation": "2025-03-06 14:30:34.458278",
                    "modified": "2025-03-06 14:30:38.160405",
                    "modified_by": "kah.yan@kingstech.com.sg",
                    "docstatus": 1,
                    "idx": 5,
                    "has_item_scanned": 0,
                    "t_warehouse": "EasyStore - SSPL",
                    "item_code": "61761598",
                    "item_name": "Wekome WDC-47 Magnetic Data Cable 65W 1M(PD 35W)",
                    "is_finished_item": 0,
                    "is_scrap_item": 0,
                    "description": "Wekome Magnetic Data Cable 66W: a cutting-edge, tangle-free solution for your charging and data transfer needs. Featuring an innovative magnetic design, this cable automatically rolls up for easy storage, eliminating clutter. The adjustable length en",
                    "item_group": "Cables",
                    "image": "https://cdn.store-assets.com/s/1374789/i/83081961.jpg",
                    "qty": 100.0,
                    "transfer_qty": 100.0,
                    "retain_sample": 0,
                    "uom": "Unit",
                    "stock_uom": "Unit",
                    "conversion_factor": 1.0,
                    "sample_quantity": 0,
                    "basic_rate": 5.0,
                    "additional_cost": 0.0,
                    "valuation_rate": 5.0,
                    "allow_zero_valuation_rate": 0,
                    "set_basic_rate_manually": 0,
                    "basic_amount": 500.0,
                    "amount": 500.0,
                    "expense_account": "6-S00007 - Stock adjustment - SSPL",
                    "cost_center": "Main - SSPL",
                    "actual_qty": 0.0,
                    "transferred_qty": 0.0,
                    "allow_alternative_item": 0,
                    "parent": "MAT-STE-2025-00026",
                    "parentfield": "items",
                    "parenttype": "Stock Entry",
                    "doctype": "Stock Entry Detail"
                }
            ]
        }
    ],
    "docinfo": {
        "user_info": {},
        "comments": [],
        "shared": [],
        "assignment_logs": [],
        "attachment_logs": [],
        "info_logs": [],
        "like_logs": [],
        "workflow_logs": [],
        "doctype": "Stock Entry",
        "name": "MAT-STE-2025-00026",
        "attachments": [],
        "communications": [],
        "automated_messages": [],
        "total_comments": 0,
        "versions": [
            {
                "name": 10499,
                "owner": "kah.yan@kingstech.com.sg",
                "creation": "2025-03-06 14:30:39.109532",
                "data": "{\"added\":[],\"changed\":[[\"posting_time\",\"14:30:34\",\"14:30:38\"],[\"docstatus\",0,1]],\"data_import\":null,\"removed\":[],\"row_changed\":[],\"updater_reference\":null}"
            }
        ],
        "assignments": [],
        "permissions": {
            "if_owner": {},
            "has_if_owner_enabled": false,
            "select": 0,
            "read": 1,
            "write": 1,
            "create": 1,
            "delete": 1,
            "submit": 1,
            "cancel": 1,
            "amend": 1,
            "print": 1,
            "email": 1,
            "report": 1,
            "import": 1,
            "export": 1,
            "set_user_permissions": 0,
            "share": 1
        },
        "views": [],
        "energy_point_logs": [],
        "additional_timeline_content": [],
        "milestones": [],
        "is_document_followed": null,
        "tags": "",
        "document_email": null
    },
    "_link_titles": {}
}
]'''

inventories = json.loads(inventories)

@router.get("/api/inventories")
async def get_inventories():
    return inventories